안드로이드 API 30 대응, 식당 리스트 순서 Fix
wafflestudio/siksha-android pull request #14
Opened 2021-04-05 14:28 UTC by veldic

2021-04-06 00:09 UTC, veldic commented
API 30에 대한 부분은 [링크](https://developers.google.com/maps/documentation/android-sdk/controls#map_toolbar)의
![image](https://user-images.githubusercontent.com/50933769/113641034-bb456180-96b7-11eb-8260-a0626f8af7bd.png)
부분을 참고하였습니다.

2021-04-07 13:55 UTC, sanggggg requested changes

2021-04-07 13:55 UTC, sanggggg commented on app/src/main/java/com/wafflestudio/siksha2/ui/main/restaurant/DailyRestaurantViewModel.kt
> +                val sortedMenuGroups = menuGroups.sortedByDescending { it.id }
추가적인 sorting 이 아니라 Dao 에서 내려오는 `getDailyMenuFlow` 나 `getAll` 의 쿼리에 `ORDERED BY id DESC` 를 붙여서 `getSortedDailyMenuFlow`, `getAllSorted` 같은 함수로 내려주는 것도 나쁘지 않아 보여요. (sqlite 에서 알아서 소팅해서 내려주는게 더 빠를 것 같음 + 이렇게 변경된다면 소팅안된 것을 가져올 일은 없으니 계속 소팅하는게 중복 로직이니까?)

2021-04-08 00:24 UTC, veldic commented on app/src/main/java/com/wafflestudio/siksha2/ui/main/restaurant/DailyRestaurantViewModel.kt
> +                val sortedMenuGroups = menuGroups.sortedByDescending { it.id }
최대한 기본 코드의 수정을 적게 하려는 방향으로 생각하다보니 저런 식으로 구현을 해놓았는데 그런 방식으로 변경하면 확실히 더 좋은 코드가 되겠네요
그 방향으로 수정해보겠습니다

2021-04-10 13:47 UTC, sanggggg commented
기록용

viewModel 에 필요없는 데이터가 많이 존재함 -> order, showEmpty 등을 레포지토리 단에서 처리해서 내려줘도 좋을 듯

2021-04-11 06:15 UTC, merged