로그아웃 시 소셜로그인 정보 남아있던 버그 수정
wafflestudio/siksha-android pull request #18
Opened 2021-04-12 12:08 UTC by veldic

google api 이용 시에 context 정보가 필요해서 context를 넘기는 식으로 코드를 짰는데 이 쪽 조언 부탁드립니다!
context를 넘겨도 될지 모르겠네요...

2021-04-12 12:24 UTC, sanggggg requested changes
보면 google 이나 kakao 로그인 로그아웃 모두 context 를 필요로 하는데, 이건 사실 applicationContext 를 받아 보면 되어서 따로 context 를 넘겨주기 보다는 `UserStateManager` 에서 `@ApplicationContext` 로 생성자에 인젝션 받고 그거 가져다가 써도 될 것 같아요

기왕 이렇게 하는김에 SplashActivity 에 있는 login 로직도 StateManager 쪽으로 가져와도 좋구요.

다만 걱정되는건 Google login 의 경우 activity 를 필요로 하기 때문에... 완전 생각한 것 처럼 모든걸 StateManager 에서 깔끔하게 처리하는 그림은 잘 안나올 것 같네요 ㅠ


당장 바꿀 필요는 없고 대신 저희가 따로 이슈 트래킹 제대로 하는 툴 없는 것 같아서 코드에 TODO 로 위 내용 남겨줘도 좋을 것 같아요 nullablepreference 처럼!

2021-04-12 12:24 UTC, sanggggg commented on app/src/main/java/com/wafflestudio/siksha2/preferences/SikshaPrefObjects.kt
> +        )
Nullable Preference 가 없어서... ㅠㅠ 
위에 주석 정도 남겨놓는게 좋을 것 같아요
```suggestion
        // TODO: nullable preference 만들어서 초기값 null 로 두기, 임시로 kakao 로 설정
        Preference(
            "oAuthProvider",
            OAuthProvider.KAKAO,
            sharedPreferences,
            serializer,
            OAuthProvider::class.java
        )
```

2021-04-12 12:24 UTC, sanggggg commented on app/src/main/java/com/wafflestudio/siksha2/repositories/UserStatusManager.kt
> +                        context.showToast("로그아웃 실패!")
문구가 조금 장난스러운 거 같은데 `로그아웃에 실패하였습니다.` 나 `로그아웃 실패` 정도로 바꾸고, 놓친 것들도 있긴 하지만 앞으로 라도 번역가능한 문자열은 string.xml 로 관리합시다!

2021-04-12 12:24 UTC, sanggggg commented on app/src/main/java/com/wafflestudio/siksha2/repositories/UserStatusManager.kt
> +                val googleSignInClient = GoogleSignIn.getClient(context, gso)
SplashActivity 에 gso 따로 더 두는 코드가 중복인 것 같은데, 합치는 방법도 있을 것 같습니다
(당장 고칠 필요는 x)

2021-04-12 12:26 UTC, sanggggg commented on app/src/main/java/com/wafflestudio/siksha2/repositories/UserStatusManager.kt
> +                    }
error 가 없으면 토스트도 안 띄우는데 의도한 상황 맞나요?
`UserApiClient.instance.logout` 에서 언제 error 를 null 로 주는지 확인하고 맥락 반영해서 이렇게 짜신거면 상관 없습니다

2021-04-12 13:55 UTC, veldic commented on app/src/main/java/com/wafflestudio/siksha2/repositories/UserStatusManager.kt
> +                        context.showToast("로그아웃 실패!")
엌 그러네요 왜 저렇게 했지...

2021-04-12 13:55 UTC, veldic commented on app/src/main/java/com/wafflestudio/siksha2/repositories/UserStatusManager.kt
> +                    }
네 맞습니다! 의도된거에요

2021-04-12 13:58 UTC, veldic commented
일단 context 부분은 어차피 activity가 필요한 방식이라 applicationContext를 주입받는 방식보다는 기존 구현해놓은 방식이 코드가 깔끔할 것 같아서 그냥 놔뒀습니다. strings.xml은 수정했어요!

2021-04-12 13:58 UTC, veldic commented on app/src/main/java/com/wafflestudio/siksha2/preferences/SikshaPrefObjects.kt
> +        )
주석 추가했습니다!

2021-04-14 15:02 UTC, sanggggg commented
[기록용]
구두전달한 내용
- 회원 탈퇴 시에도 oauth sdk 에서 잘 처리해주기
- `error?.let {}` 코드 if 문으로 바꾸기...?

2021-04-21 04:42 UTC, veldic commented
카카오는 로그아웃 시 error가 와도 token은 삭제된다고 합니다.

2021-05-20 05:10 UTC, merged