하트 작업 fin!
wafflestudio/siksha-android pull request #39
Opened 2023-09-02 18:56 UTC by seozzi

하트 작업 완료했습니다!! DailyRestaurantFragment와 MenuDetailFragment에서 버튼 like/unlike 하는 동작 .webm 첨부하겠습니다~!!

애뮬레이터 돌릴 수 있는 환경을 개선하게 되어서 테스트해보니 기존 제 코드가 얼마나 정상 동작과 거리가 멀었는지 알게되었습니다..ㅠ
하나하나 꼼꼼히 리뷰해주신 점 정말 감사드리고 기다리게 해드려 죄송합니다!ㅠㅠ

이번 리뷰도 잘 부탁드립니다! ㅎㅎ

2023-09-02 20:13 UTC, seozzi commented
말씀드린 gif 파일입니다!
![heart_functionality](https://github.com/wafflestudio/siksha-android/assets/110961253/f9ab89b9-5146-4ed7-937f-96001965f555)

그나저나 위의 3개 체크 중에 두 번째 거는 가벼운 오류들이라 쉽게 해결했는데 세 번째 오류는 여기에 google-services.json을 안 올렸다며 뜨더라구요..! 이건 private하게 전달해주셨기도 해서 그냥 놔뒀는데.. 어떻게 해야 할까요? 이대로 리뷰받구 괜찮으면 이 세 번째 오류는 무시하고 머지해도 되는 건가요?

2023-09-10 06:21 UTC, sanggggg requested changes

2023-09-10 06:21 UTC, sanggggg commented on app/src/main/res/layout/item_menu_group.xml
> +<!--여기 rate, like constraint-->
```suggestion
```

🔪

2023-09-10 06:21 UTC, sanggggg commented on app/src/main/java/com/wafflestudio/siksha2/components/RateTextView.kt
> +//        else binding.menuScore.setBackgroundResource(R.drawable.frame_rate_text_red)
```suggestion
```

🔪

2023-09-10 06:21 UTC, sanggggg commented on app/src/main/java/com/wafflestudio/siksha2/network/SikshaApi.kt
> +    suspend fun unlikeMenu(@Path("menu_id") menuId: Long): MenuLikeResponse
`MenuUnlikeResponse` ?

2023-09-10 06:21 UTC, sanggggg commented on app/src/main/java/com/wafflestudio/siksha2/ui/main/restaurant/DailyRestaurantFragment.kt
> +                Log.d(TAG, "fragment observing vm/ Let's go to the menuGroupAdapter to refresh the menu. It should be ${menuItem.isLiked}")
```suggestion
```

앞으로도 자주 보고 싶을 수 있는 Log 가 아니라면 Debug 레벨이라도 작업 완료 후 지우는게 좋을 것 같아요.

2023-09-10 06:21 UTC, sanggggg commented on app/src/main/java/com/wafflestudio/siksha2/ui/main/restaurant/DailyRestaurantViewModel.kt
> +            _updatedMenuItemStream.postValue(menuItem)
오 터치한 즉시 (네트워크 응답 이전에) 사용자 피드백 주려고 하는 코드로 보이는 데 좋은 UX 일 것 같아요 👍

2023-09-10 06:21 UTC, sanggggg commented on app/src/main/java/com/wafflestudio/siksha2/ui/main/restaurant/DailyRestaurantFragment.kt
> +                Log.d(TAG, "fragment observing vm/ Let's go to the menuGroupAdapter to refresh the menu. It should be ${menuItem.isLiked}")
이건 이 Log.d 뿐 아니라 이번 PR 에서 추가된 다른 곳에도 대응해 주시면 좋을 것 같습니다.

2023-09-10 06:21 UTC, sanggggg commented on app/src/main/java/com/wafflestudio/siksha2/ui/main/restaurant/DailyRestaurantViewModel.kt
> +            startRefreshingData()
요렇게 리프레시 해 주시면 동일한 메뉴가 다른 시간대에서 좋아요 해도, 현재 사용자가 보고 있는 상태에도 싱크를 맞춰줄 수 있어서 이전에 있었던 문제가 잘 해결되었을 것 같네요 👍

2023-09-10 06:21 UTC, sanggggg commented on app/src/main/java/com/wafflestudio/siksha2/ui/menuDetail/MenuDetailFragment.kt
> +            }
[nit]
현재 xml 기준으로 `android:text` 가 `좋아요 43개` 로 되어 있어서, 서버에서 이 값을 null 로 내려준 경우에는 해당 텍스트가 그대로 남아서 유저한테 이상한 정보를 내려줄 수 있을 것 같아요.

1. `android:text` 대신 `tools:text` 로 `좋아요 43개` 를 넣어주고, 기본 텍스트는 `-` 나 공백 처럼 중립적으로 두기
2. 또는 `menu.isLiked` 가 null 이면 `-` 공백 처럼 중립적으로 두기기.
```kt
binding.menuLikeCount.text = menu.likeCount?.let { "좋아요 $it 개" } ?: "-"`
```

안전빵으로 두 방식을 다 해줘도 좋을 것 같아요.

2023-09-10 06:21 UTC, sanggggg commented on app/src/main/java/com/wafflestudio/siksha2/ui/menuDetail/MenuDetailFragment.kt
> +            }
[nit]
```kt
vm.menu.value?.isLiked?.let {
    vm.toggleLike(args.menuId, it)
}
```

2023-09-10 06:21 UTC, sanggggg commented on app/src/main/java/com/wafflestudio/siksha2/ui/menuDetail/MenuDetailViewModel.kt
> +            if (serverMenuItem.isLiked != menuItem.isLiked) {
```kt
serverMenuItem != menuItem
```
이어도 좋을 것 같아요. Liked 변화 뿐 아니라 카운트 변화 까지 가장 최신 서버 상태를 무조건 반영할 수 있도록

2023-09-10 06:21 UTC, sanggggg commented on app/src/main/res/drawable/ic_full_heart_small.png
이전 PR 에서 언급한 svg 쓰기!

2023-09-10 06:21 UTC, sanggggg commented on app/src/main/res/layout/item_menu_group.xml
> +            android:id="@+id/like_info"
이 뷰 Constraint 가 안 걸려있는 느낌인데 추가해 줘야 할 것 같아요
rate_info 의 end_to_start
parent 의 end_to_end, top_to_top, bottom_to_bottom?

2023-09-10 06:49 UTC, sanggggg commented on app/build.gradle.kts
> +    id("com.android.application") version "8.0.2"
혹시 버전을 낮춘 이유가 있으신가요?

2023-09-10 07:25 UTC, sanggggg commented
> 그나저나 아래 CI 3개 체크 중에 두 번째 거는 가벼운 오류들이라 쉽게 해결했는데 세 번째 오류는 여기에 google-services.json을 안 올렸다며 뜨더라구요..! 이건 private하게 전달해주셨기도 해서 그냥 놔뒀는데.. 어떻게 해야 할까요? 이대로 리뷰받구 괜찮으면 이 세 번째 오류는 무시하고 머지해도 되는 건가요?

이 문제 디버깅해보려고 branch 받아서 빌드를 시도하니 AGP 버전이 내려가면서 android compileOptions 의 타겟 jvm 이 toolchain 버전을 따라가지 못하는 이슈가 있는 것 같습니다.
그래서 다시 이전 버전인 8.1.0 으로 돌려놓고 빌드를 하거나, compileOptions 를 명시적으로 주니 빌드 & CI 가 google-services.json 문제 없이 잘 되는 것 같아서, 해당 문제도 agp 버전을 내릴 때 발생한 사이드 이펙트 성 문제인 것 같아요, 더 파보지는 않았습니다. #40 

따라서 AGP 버전을 8.1.0 으로 돌려주면 해결 될 거라 이 부분 PR 에 반영해주시면 될 것 같습니다. (엄밀히는 기존에 8.1.0-alpha 를 쓰고 있었는데, 이것도 그냥 stable 한 8.1.0 나왔으니 8.1.0 으로 바꿔주시면 될 것 같아요)

2023-09-10 08:06 UTC, seozzi commented on app/src/main/java/com/wafflestudio/siksha2/network/SikshaApi.kt
> +    suspend fun unlikeMenu(@Path("menu_id") menuId: Long): MenuLikeResponse
아하 이건 Menu like/unlike 했을 때 돌아오는 건데 애초에 이렇게 생겼어서: 
typealias MenuLikeResponse = Menu
따로 MenuUnlikeResponse를 두기 보단 변수명을 MenuLikeOrUnlikeResponse 로 변경하겠습니다!!

2023-09-10 08:25 UTC, seozzi commented on app/src/main/java/com/wafflestudio/siksha2/ui/main/restaurant/DailyRestaurantFragment.kt
> +                Log.d(TAG, "fragment observing vm/ Let's go to the menuGroupAdapter to refresh the menu. It should be ${menuItem.isLiked}")
넵 fragment랑 viewmodel에 포함되어 있던 log.d 다 삭제 완료했습니다!!

2023-09-10 08:33 UTC, seozzi commented on app/src/main/java/com/wafflestudio/siksha2/ui/menuDetail/MenuDetailFragment.kt
> +            }
넵 1 2번 둘다 적용했슴다!

2023-09-10 08:38 UTC, seozzi commented on app/src/main/java/com/wafflestudio/siksha2/ui/menuDetail/MenuDetailViewModel.kt
> +            if (serverMenuItem.isLiked != menuItem.isLiked) {
오호 좋습니다!!

2023-09-10 09:56 UTC, seozzi commented on app/src/main/res/drawable/ic_full_heart_small.png
svg 파일로 변경했습니다!

2023-09-10 10:22 UTC, seozzi commented on app/src/main/res/layout/item_menu_group.xml
> +            android:id="@+id/like_info"
앗 확인해보니 rate_info like_info 모두 start는 없지만 end는 parent로 걸려 있고 marginEnd 각 44 16dp로 배치해놓으신 것 같아요!!
이대로 해도 괜찮을까용?

2023-09-10 10:38 UTC, seozzi commented on app/src/main/res/drawable/ic_full_heart_small.png
앗.. svg 파일로 바꾸려 하다보니 벡터 이미지로는 변환이 간단히 안 되는 것 같습니다ㅠㅠ 피그마에서 추출해온 svg 파일에 기본적으로 <image> 내용과 <pattern> 내용도 들어가 있는데 그게 android studio의 vector drawable asset에서는 자동변환 지원을 안해주는 것 같더라구요ㅠㅠ 일단 png로 릴리즈를 하고 이걸 벡터 이미지로 어떻게 바꾸면 될지는 제가 디자이너님께 여쭈어 볼게요!!

2023-09-10 10:57 UTC, sanggggg commented on app/src/main/res/layout/item_menu_group.xml
> +            android:id="@+id/like_info"
넵 제가 코드를 잘못 봤었네요 👍

2023-09-10 10:59 UTC, seozzi commented
위 내용 다 추가해서(svg 파일 문제만 아직 남겨둔 채로) 새로 커밋 올렸습니다! 커밋을 한꺼번에 해서 커밋 해시가 한 데 합쳐져 버렸네요..ㅠㅠ 다음부턴 각 수정 항목 별 커밋 만들어서 각 이슈 아래 댓글로 커밋 해시 남겨두겠습니다!! 
c45c7b42d8975cdd639923f6fbbab57d39483fb3

위 내용 다 고치고 애뮬레이터 돌린 결과 빌드도 잘 되고 별다른 동작성 변화 없이 잘 돌아가는 것 같습니다~!

2023-09-10 11:36 UTC, sanggggg commented
> > 그나저나 아래 CI 3개 체크 중에 두 번째 거는 가벼운 오류들이라 쉽게 해결했는데 세 번째 오류는 여기에 google-services.json을 안 올렸다며 뜨더라구요..! 이건 private하게 전달해주셨기도 해서 그냥 놔뒀는데.. 어떻게 해야 할까요? 이대로 리뷰받구 괜찮으면 이 세 번째 오류는 무시하고 머지해도 되는 건가요?
> 
> 이 문제 디버깅해보려고 branch 받아서 빌드를 시도하니 AGP 버전이 내려가면서 android compileOptions 의 타겟 jvm 이 toolchain 버전을 따라가지 [못하는 이슈](https://issuetracker.google.com/issues/260059413?pli=1)가 있는 것 같습니다. (아마 8.0.2 에는 아예 없는 기능이었을 듯) 그래서 다시 이전 버전인 8.1.0 으로 돌려놓고 빌드를 하거나, compileOptions 를 명시적으로 주니 빌드 & CI 가 google-services.json 문제 없이 잘 되는 것 같아서, 해당 문제도 agp 버전을 내릴 때 발생한 사이드 이펙트 성 문제인 것 같아요, 더 파보지는 않았습니다. #40
> 
> 따라서 AGP 버전을 8.1.0 으로 돌려주면 해결 될 거라 이 부분 PR 에 반영해주시면 될 것 같습니다. (엄밀히는 기존에 8.1.0-alpha 를 쓰고 있었는데, 이것도 그냥 stable 한 8.1.0 나왔으니 8.1.0 으로 바꿔주시면 될 것 같아요)

[기록용] 이거 생각해보니 fork 된 레포에서 Action 이 돌아서 secret 을 못 찾고 뜨는 에러같네요, PR approve 후에 main repo 의 브랜치 형태로 PR 다시 쏴 주시면 거기서 머지하면 될 것 같습니다

2023-09-10 13:20 UTC, seozzi commented
앗 방금 approve 하려고 들어가 보니까 PR author는 자기 PR approve할 수가 없다고 떠서요,,ㅠㅠ 혹시 approve 부탁드려도 될까요?

2023-09-10 14:53 UTC, sanggggg requested changes

2023-09-10 14:53 UTC, sanggggg commented on app/src/main/java/com/wafflestudio/siksha2/repositories/MenuRepository.kt
> +            Log.d(TAG, "repo called from vm/ Just liked the menu!")
Log.d 날리기

2023-09-10 14:53 UTC, sanggggg commented on app/src/main/java/com/wafflestudio/siksha2/ui/main/restaurant/MenuGroupAdapter.kt
> +                return
refresh 를 이런 식으로 해 주는 것 보다, submitList 를 다시 해주는 형태로 하는게 좀 더 깔끔할 것 같아요,

자식 ViewHolder 의 구현을 알 필요 없이 `submitList(modifiedList)` 를 호출하면, 자식에도 Diff 가 발생해서 자연스럽게 변경이 전달될 것 같아요.

2023-09-11 05:21 UTC, seozzi commented
말씀해주신 두 가지 내용 모두 반영해서 커밋해 놓았습니다!! 
c5af182d9c3e225b73697c6821672eb9d07a1de3
마지막으로 한 번 더 체크해 본 결과 서버측에서 보수해야 할 내용 빼고 안드 동작성은 문제 없는 것 같다 생각합니다..! 그럼 이제 머지하고.. 릴리즈.. 드디어 하는 건가용!?!🫢

2023-09-30 10:05 UTC, sanggggg approved these changes

2023-09-30 10:07 UTC, sanggggg commented
[기록용] Clone repo 에 Secret 없어서 & 제 Push 권한이 없어서 포스 머지한 후에 린트 픽스 및 CI 돌릴 예정

2023-09-30 10:07 UTC, merged